name: Build APK

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up environment
      run: |
        mkdir -p ~/android-sdk
        mkdir -p ~/.android
        touch ~/.android/repositories.cfg

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y zip unzip openjdk-17-jdk python3-pip wget

    - name: Install Python dependencies
      run: |
        pip install cython==0.29.36 buildozer kivy==2.3.0

    - name: Install Android SDK (SOLUCIÓN DEFINITIVA)
      run: |
        # 1. Descargar Command Line Tools
        wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
        unzip commandlinetools-linux-*.zip -d tmp-cmdline
        
        # 2. Crear estructura CORRECTA (2023+)
        mkdir -p ~/android-sdk/cmdline-tools/latest
        mv tmp-cmdline/cmdline-tools/* ~/android-sdk/cmdline-tools/latest/
        rm -rf tmp-cmdline
        
        # 3. Configurar variables de entorno
        echo "ANDROID_HOME=~/android-sdk" >> $GITHUB_ENV
        echo "PATH=~/android-sdk/cmdline-tools/latest/bin:$PATH" >> $GITHUB_ENV
        
        # 4. SOLUCIÓN CLAVE: Forzar ruta correcta en buildozer.spec
        echo -e "\n[buildozer]\nandroid.sdkmanager = ~/android-sdk/cmdline-tools/latest/bin/sdkmanager" >> buildozer.spec
        
        # 5. Verificación crítica
        echo "=== Verificando instalación ==="
        ls -la ~/android-sdk/cmdline-tools/latest/bin/
        
        # 6. Aceptar licencias e instalar componentes
        yes | ~/android-sdk/cmdline-tools/latest/bin/sdkmanager --licenses
        ~/android-sdk/cmdline-tools/latest/bin/sdkmanager "build-tools;34.0.0" "platform-tools" "platforms;android-34"

    - name: Install Android NDK
      run: |
        wget https://dl.google.com/android/repository/android-ndk-r25b-linux.zip
        unzip android-ndk-r25b-linux.zip -d ~/android-sdk
        echo "ANDROID_NDK_HOME=~/android-sdk/android-ndk-r25b" >> $GITHUB_ENV
        echo -e "\nandroid.ndk_path = ~/android-sdk/android-ndk-r25b" >> buildozer.spec

    - name: Build APK
      run: |
        # Configuración final
        echo "=== buildozer.spec final ==="
        cat buildozer.spec
        
        buildozer -v android debug
        ls bin/

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: App-Android
        path: bin/*.apk
