name: Build APK

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up environment
      run: |
        mkdir -p ~/android-tools
        mkdir -p ~/.android
        touch ~/.android/repositories.cfg

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y zip unzip openjdk-17-jdk python3-pip wget

    - name: Install Python dependencies
      run: |
        pip install cython==0.29.36 buildozer kivy==2.3.0

    - name: Install Android SDK
      run: |
        # Descarga Command Line Tools
        wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
        unzip commandlinetools-linux-*.zip -d cmdline-tools
        mkdir -p cmdline-tools/latest
        mv cmdline-tools/cmdline-tools/* cmdline-tools/latest/
        
        # Configura variables de entorno (CRUCIAL)
        echo "ANDROID_HOME=$PWD/cmdline-tools" >> $GITHUB_ENV
        echo "ANDROID_SDK_ROOT=$PWD/cmdline-tools" >> $GITHUB_ENV
        echo "$PWD/cmdline-tools/latest/bin" >> $GITHUB_PATH
        
        # Verifica instalación
        ls -la $PWD/cmdline-tools/latest/bin/
        ./cmdline-tools/latest/bin/sdkmanager --list

    - name: Accept licenses and install packages
      run: |
        yes | ./cmdline-tools/latest/bin/sdkmanager --licenses
        ./cmdline-tools/latest/bin/sdkmanager "build-tools;34.0.0" "platform-tools" "platforms;android-34"

    - name: Install Android NDK
      run: |
        wget https://dl.google.com/android/repository/android-ndk-r25b-linux.zip
        unzip android-ndk-r25b-linux.zip -d ~/android-tools
        mv ~/android-tools/android-ndk-r25b ~/android-tools/android-ndk
        echo "ANDROID_NDK_HOME=$HOME/android-tools/android-ndk" >> $GITHUB_ENV

    - name: Build APK
      run: |
        echo "[buildozer]" > buildozer.spec
        echo "android.ndk_path = $HOME/android-tools/android-ndk" >> buildozer.spec
        echo "android.sdk_path = $ANDROID_HOME" >> buildozer.spec
        
        buildozer -v android debug
        ls bin/

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: App-Android
        path: bin/*.apk
