name: Build APK

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up environment
      run: |
        mkdir -p ~/android-sdk
        mkdir -p ~/.android
        touch ~/.android/repositories.cfg

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y zip unzip openjdk-17-jdk python3-pip wget

    - name: Install Python dependencies
      run: |
        pip install cython==0.29.36 buildozer kivy==2.3.0

    - name: Install Android SDK
      run: |
        # Descarga Command Line Tools
        wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
        unzip commandlinetools-linux-*.zip -d ~/android-sdk/cmdline-tools
        
        # Configura paths correctos
        echo "ANDROID_HOME=~/android-sdk" >> $GITHUB_ENV
        echo "ANDROID_SDK_ROOT=~/android-sdk" >> $GITHUB_ENV
        echo "PATH=~/android-sdk/cmdline-tools/bin:$PATH" >> $GITHUB_ENV
        
        # Acepta licencias e instala componentes
        yes | ~/android-sdk/cmdline-tools/bin/sdkmanager --licenses
        ~/android-sdk/cmdline-tools/bin/sdkmanager "build-tools;34.0.0" "platform-tools" "platforms;android-34"

    - name: Install Android NDK
      run: |
        wget https://dl.google.com/android/repository/android-ndk-r25b-linux.zip
        unzip android-ndk-r25b-linux.zip -d ~/android-sdk
        echo "ANDROID_NDK_HOME=~/android-sdk/android-ndk-r25b" >> $GITHUB_ENV

    - name: Configure build
      run: |
        # Actualiza buildozer.spec con rutas correctas
        echo "ANDROID_HOME: $ANDROID_HOME"
        echo "ANDROID_NDK_HOME: $ANDROID_NDK_HOME"
        sed -i "s|android.sdk_path = .*|android.sdk_path = $ANDROID_HOME|" buildozer.spec
        sed -i "s|android.ndk_path = .*|android.ndk_path = $ANDROID_NDK_HOME|" buildozer.spec
        cat buildozer.spec

    - name: Build APK
      run: |
        buildozer -v android debug
        ls bin/

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: App-Android
        path: bin/*.apk
