name: Build APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04   # <-- fijamos 22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install system deps
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            openjdk-17-jdk \
            zip unzip git build-essential \
            libffi-dev libssl-dev libjpeg-dev libsqlite3-dev \
            libxml2-dev libxslt1-dev zlib1g-dev \
            libtool automake autoconf

      - name: Install Buildozer & Kivy
        run: |
          python -m pip install --upgrade pip
          pip install buildozer cython kivy

      - name: Cache Buildozer global dir
        uses: actions/cache@v3
        with:
          path: ~/.buildozer
          key: buildozer-${{ runner.os }}-${{ hashFiles('buildozer.spec') }}

      - name: Build APK
        run: |
          buildozer -v android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: bin/*.apk
