name: Build APK

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up environment
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          zip unzip openjdk-17-jdk \
          wget autoconf libtool \
          pkg-config zlib1g-dev

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install cython==0.29.36 buildozer kivy==2.3.0

    - name: Install Android SDK/NDK
      run: |
        # Install Android Command Line Tools
        wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
        unzip commandlinetools-linux-*.zip -d cmdline-tools
        mkdir -p cmdline-tools/latest
        mv cmdline-tools/cmdline-tools/* cmdline-tools/latest/
        
        # Create symlink for backward compatibility
        mkdir -p cmdline-tools/tools
        ln -s ../latest cmdline-tools/tools/bin
        
        # Accept licenses and install components
        yes | cmdline-tools/latest/bin/sdkmanager --licenses
        cmdline-tools/latest/bin/sdkmanager "build-tools;34.0.0" "platform-tools" "platforms;android-34"
        
        # Install NDK
        wget https://dl.google.com/android/repository/android-ndk-r25b-linux.zip
        unzip android-ndk-r25b-linux.zip -d ~/
        
        echo "ANDROID_HOME=$PWD/cmdline-tools" >> $GITHUB_ENV
        echo "ANDROID_NDK_HOME=~/android-ndk-r25b" >> $GITHUB_ENV
        echo "PATH=$PWD/cmdline-tools/latest/bin:$PATH" >> $GITHUB_ENV

    - name: Build APK
      run: |
        # Fix build issues
        export LT_SYS_SYMBOL_USCORE=no
        
        # SOLUCIÓN CLAVE: Actualizar config existente sin duplicar sección
        sed -i '/^android\.sdkmanager/d' buildozer.spec
        sed -i '/^android\.ndk_path/d' buildozer.spec
        sed -i '/^android\.archs/d' buildozer.spec
        
        # Añadir configuraciones al final del archivo (sin crear nueva sección)
        echo "android.sdkmanager = $PWD/cmdline-tools/latest/bin/sdkmanager" >> buildozer.spec
        echo "android.ndk_path = $HOME/android-ndk-r25b" >> buildozer.spec
        echo "android.archs = arm64-v8a" >> buildozer.spec
        
        buildozer -v android debug
        ls bin/

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: App-Android
        path: bin/*.apk
