name: Build APK

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up environment
      run: |
        mkdir -p ~/android-sdk
        mkdir -p ~/.android
        touch ~/.android/repositories.cfg

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y zip unzip openjdk-17-jdk python3-pip wget

    - name: Install Python dependencies
      run: |
        pip install cython==0.29.36 buildozer kivy==2.3.0

    - name: Install Android SDK
      run: |
        # Descargar Command Line Tools
        wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
        unzip commandlinetools-linux-*.zip -d tmp-cmdline
        
        # Mover a estructura correcta
        mkdir -p ~/android-sdk/cmdline-tools/latest
        mv tmp-cmdline/cmdline-tools/* ~/android-sdk/cmdline-tools/latest/
        rm -rf tmp-cmdline
        
        # Configurar variables
        echo "ANDROID_HOME=~/android-sdk" >> $GITHUB_ENV
        echo "PATH=~/android-sdk/cmdline-tools/latest/bin:$PATH" >> $GITHUB_ENV
        
        # SOLUCIÓN CLAVE: Especificar ruta exacta del sdkmanager
        echo "android.sdkmanager = ~/android-sdk/cmdline-tools/latest/bin/sdkmanager" >> buildozer.spec

        # Aceptar licencias e instalar componentes
        yes | ~/android-sdk/cmdline-tools/latest/bin/sdkmanager --licenses
        ~/android-sdk/cmdline-tools/latest/bin/sdkmanager "build-tools;34.0.0" "platform-tools" "platforms;android-34"

    - name: Install Android NDK
      run: |
        wget https://dl.google.com/android/repository/android-ndk-r25b-linux.zip
        unzip android-ndk-r25b-linux.zip -d ~/android-sdk
        echo "ANDROID_NDK_HOME=~/android-sdk/android-ndk-r25b" >> $GITHUB_ENV
        echo "android.ndk_path = ~/android-sdk/android-ndk-r25b" >> buildozer.spec

    - name: Configure build
      run: |
        # Actualizar rutas en buildozer.spec
        sed -i "s|android.sdk_path = .*|android.sdk_path = $ANDROID_HOME|" buildozer.spec
        
        echo "=== buildozer.spec actualizado ==="
        cat buildozer.spec

    - name: Build APK
      run: |
        # Configurar variables de entorno
        export ANDROID_SDK_ROOT=$ANDROID_HOME
        export ANDROID_NDK_HOME=$ANDROID_NDK_HOME
        
        buildozer -v android debug
        ls bin/

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: App-Android
        path: bin/*.apk
