name: Build APK

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y zip unzip openjdk-17-jdk python3-pip wget
        # Configura Android SDK
        mkdir -p ~/.android
        touch ~/.android/repositories.cfg
        wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
        unzip commandlinetools-linux-*.zip -d cmdline-tools
        mv cmdline-tools/cmdline-tools cmdline-tools/latest
        export ANDROID_HOME=$PWD/cmdline-tools
        export PATH=$PATH:$ANDROID_HOME/latest/bin
        yes | sdkmanager --licenses
        sdkmanager "build-tools;34.0.0" "platform-tools" "platforms;android-34"
        # Dependencias Python
        pip install cython==0.29.36 buildozer kivy==2.3.0

    - name: Build APK
      run: |
        export PATH=$PATH:$PWD/cmdline-tools/latest/bin
        buildozer -v android debug
        ls bin/

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: App-Android
        path: bin/*.apk
