name: Build APK

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y zip unzip openjdk-17-jdk
        pip install buildozer kivy

    - name: Build APK
      run: |
        buildozer android debug
        ls bin/  # Verifica que el .apk existe

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: App-Android
        path: bin/*.apk
